import Auth from '@/components/Auth/Auth';
import Messenger from '@/components/Messenger/Messenger';
import { GetServerSideProps } from 'next';
import { getServerSession, Session } from 'next-auth';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { authOptions } from './api/auth/[...nextauth]';

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session?.user ? <Messenger /> : <Auth />}
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  session?: Session | null;
}> = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (!session) {
    return {
      props: {},
    };
  }

  return {
    props: {
      session,
    },
  };
};
